# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Darwin_x86_64.tar.gz"
      sha256 "712573e384c3d7a6e7f678d3ec69667630d3208e75c96c4e9498378206ad69c5"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Darwin_arm64.tar.gz"
      sha256 "6e00dde99ba350606a858600dd4f7e366f39dd899986c5fcc6777f27ba64811d"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Linux_x86_64.tar.gz"
      sha256 "57b6d3434e6ed9fa0925df6dfbddecd9f543ade406b4b7dfe81f2c35e3cfa58b"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Linux_arm64.tar.gz"
      sha256 "b3e9d4f4ab71d11b59e716ea9e2a785dda13c9db49ae0ac9d97600e4f65e51db"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    assert_match "treex version #{version}", shell_output("#{bin}/treex --version")
  end
end
