# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Darwin_x86_64.tar.gz"
      sha256 "19322a31659fc8b4f93d62c2a218f8192bcbb447ddbbd10d018395c8eecf50b7"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Darwin_arm64.tar.gz"
      sha256 "b17dbfb0571634a165db5994828a979dc9a43d2a01518dcfcc19b13713aaa385"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Linux_x86_64.tar.gz"
      sha256 "769e6899c6cd3ecff4f49339a11b4630d212cefd490ce9d4995308abceb64c7f"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.0/treex_Linux_arm64.tar.gz"
      sha256 "2eb771e9674a117c891406326cdd5a7a2eec4aa61266770f39a798418d1a7bfc"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash"
        zsh_completion.install "completions/_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    assert_match "treex version #{version}", shell_output("#{bin}/treex --version")
  end
end
