# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.1.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.21/treex_0.1.21_darwin_amd64.tar.gz"
      sha256 "b7cc855c86fc3cd1c8a189e36f37463bc603087069a8e7939078dfffdf32c9a4"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.21/treex_0.1.21_darwin_arm64.tar.gz"
      sha256 "cab3d2812c83154e6356e5624abe386c355f05c90fd9ca55a3b5fc997acdde4c"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.21/treex_0.1.21_linux_amd64.tar.gz"
      sha256 "9913ec6346f9aaac812b26c614029341a5546cd4a5776371c7546a925485bc66"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.21/treex_0.1.21_linux_arm64.tar.gz"
      sha256 "5817ec9eae38992521e2a87e17d028b1890090038ae27c343c9b0ff4ecf267db"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    system "#{bin}/treex --version"
  end
end
