# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanodoc < Formula
  desc "A minimalist document bundler"
  homepage "https://github.com/arthur-debert/nanodoc-go"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.2/nanodoc_0.0.2_darwin_amd64.tar.gz"
      sha256 "fe7b20fa810825dde9087f11b165ec255e82de805b7165105d4f05f89f3ff8c0"

      def install
        bin.install "nanodoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.2/nanodoc_0.0.2_darwin_arm64.tar.gz"
      sha256 "37111add95bdf8a8fe212b445097314a963df69e78ee69a9a5c7d61e4dd7442b"

      def install
        bin.install "nanodoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.2/nanodoc_0.0.2_linux_amd64.tar.gz"
      sha256 "b5b2a82f831098895ff166d7aa0375a2bd9fd8d08af2640bdb19c698523266d5"
      def install
        bin.install "nanodoc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.2/nanodoc_0.0.2_linux_arm64.tar.gz"
      sha256 "60f9409ac628bf02a79b7964c6869008a1fc1058d301fe867b5b744503f91d8a"
      def install
        bin.install "nanodoc"
      end
    end
  end

  test do
    system "#{bin}/nanodoc --help"
  end
end
