# This file was generated by GoReleaser. DO NOT EDIT.
cask "treex" do
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treex"
  manpage "man/man1/treex.1"
  bash_completion "completions/treex.bash"
  zsh_completion "completions/_treex"
  fish_completion "completions/treex.fish"

  on_macos do
    on_intel do
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.7/treex_Darwin_x86_64.tar.gz"
      sha256 "76952aecfeb84a2e05cce5a52ca50bbbe8d77f6ba1230fefcc21dee9eb8deeb6"
    end
    on_arm do
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.7/treex_Darwin_arm64.tar.gz"
      sha256 "b0ad5f71809fcfed074e5583bd7bfa1647a5a6067f6c53af6d44ae89d02f105b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.7/treex_Linux_x86_64.tar.gz"
      sha256 "104f85b88d3643f6a05b272ee0e010bce4db9d0d514f53ba3fe45f15b9e56337"
    end
    on_arm do
      url "https://github.com/arthur-debert/treex/releases/download/v0.1.7/treex_Linux_arm64.tar.gz"
      sha256 "5a44482c340baaffb44f8dc2f2e34a9fb4a00b6ec6855cb0c539b6b99c2d981e"
    end
  end

  # No zap stanza required
end
