# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# burgertocow ships macOS arm64 only (no intel mac in the build matrix).
# burgertocow has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts.

class Burgertocow < Formula
  desc "CLI for burgertocow: reverse-engineers diffs on rendered minijinja templates back into template or variable changes."
  homepage "https://github.com/arthur-debert/burgertocow"
  version "0.2.0-rc.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0-rc.1/burgertocow-aarch64-apple-darwin.tar.gz"
      sha256 "d1bdc416ad582368988c0aa8e3d4c11d489874e6a69b8c3a591dca858c8d5d25"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0-rc.1/burgertocow-x86_64-linux-gnu.tar.gz"
      sha256 "e1ac3dd7a95f87aaabe9bad0f746db41e8b035aab7dc5efb5ed0614551db19f0"
    end
    on_arm do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0-rc.1/burgertocow-aarch64-linux-gnu.tar.gz"
      sha256 "9a254b8de3063e6df18c731e2caab1d241d1026ad45129910cd3ff21011b544a"
    end
  end

  def install
    # Canonical subdirectory layout: burgertocow-<target>/burgertocow.
    # File.exist? handles a future flat-root layout for portability.
    executable = if File.exist?("burgertocow")
      "burgertocow"
    else
      Dir["*/burgertocow"].find { |path| File.file?(path) }
    end
    raise "Could not find burgertocow in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burgertocow --version")
  end
end
