# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# burgertocow ships macOS arm64 only (no intel mac in the build matrix).
# burgertocow has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts.

class Burgertocow < Formula
  desc "CLI for burgertocow: reverse-engineers diffs on rendered minijinja templates back into template or variable changes."
  homepage "https://github.com/arthur-debert/burgertocow"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0/burgertocow-aarch64-apple-darwin.tar.gz"
      sha256 "f805144fdf4fe4d40c6b12a8bb2b140638dc64e70252f89af947d0ef51e01a51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0/burgertocow-x86_64-linux-gnu.tar.gz"
      sha256 "2edb5ae4e355f55655e668f20beff5ca9253f4f89c9d11af5359710b9094acf0"
    end
    on_arm do
      url "https://github.com/arthur-debert/burgertocow/releases/download/v0.2.0/burgertocow-aarch64-linux-gnu.tar.gz"
      sha256 "1e0a9aa63672cb3bf727ee34b0ce6bde124f43ae0aa14d8fcedf14f0a229135a"
    end
  end

  def install
    # Canonical subdirectory layout: burgertocow-<target>/burgertocow.
    # File.exist? handles a future flat-root layout for portability.
    executable = if File.exist?("burgertocow")
      "burgertocow"
    else
      Dir["*/burgertocow"].find { |path| File.file?(path) }
    end
    raise "Could not find burgertocow in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burgertocow --version")
  end
end
