# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dodot < Formula
  desc "Description of your CLI tool"
  homepage "https://github.com/arthur-debert/dodot"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.4/dodot-cli_0.3.4_darwin_amd64.tar.gz"
      sha256 "d6623965aeac7fcbd6018851dd6fc31acd4ad222fb18c774aedc41fcd7a765a5"

      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.4/dodot-cli_0.3.4_darwin_arm64.tar.gz"
      sha256 "ff8547a8679dda5bfac7fa10cfd5219ef4e8ab61009ff67e000944f0aeea651e"

      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.4/dodot-cli_0.3.4_linux_amd64.tar.gz"
      sha256 "d785d17b9b453d2ce69e85050efbf22264900814dcbe10ebb192e4b6c098d303"
      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.4/dodot-cli_0.3.4_linux_arm64.tar.gz"
      sha256 "bfeda4aca78d71a0000e90f4828e7de3c875b4dc86537b34d1c05ca256e662c7"
      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
  end

  test do
    system "#{bin}/dodot --help"
  end
end
