# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dodot < Formula
  desc "Description of your CLI tool"
  homepage "https://github.com/arthur-debert/dodot"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.3/dodot-cli_0.3.3_darwin_amd64.tar.gz"
      sha256 "14f49dcf1c0342e72f14e21d73bf8eb95bf7b89e498221b489c7f1e142a2b2e2"

      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.3/dodot-cli_0.3.3_darwin_arm64.tar.gz"
      sha256 "7bb85c82c90341d1a5fcc588b8768c76fdb96ae9d4124d9b8ef289f86d5cc31f"

      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.3/dodot-cli_0.3.3_linux_amd64.tar.gz"
      sha256 "5b1000ea5eb7dedef30a3c9a1d481caa086e25d46781f7a023276368e89cdefc"
      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dodot/releases/download/v0.3.3/dodot-cli_0.3.3_linux_arm64.tar.gz"
      sha256 "04b730aa671f98cceabbd01836cbb2ed503e31e00d4fb41644008315951ab19c"
      def install
        bin.install "dodot"

        # Install shell completions
        bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
        zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
        fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")

        # Install man page
        man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")

        # Install shell integration scripts
        pkgshare.install "shell" if Dir.exist?("shell")

        # Install styles configuration
        pkgshare.install "styles" if Dir.exist?("styles")
      end
    end
  end

  test do
    system "#{bin}/dodot --help"
  end
end
