# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow via .github/render-homebrew-formula.py. The generated output
# is pushed to the tap repo (HOMEBREW_TAP in release.yml).
#
# dodot ships macOS arm64 only (matches the project's "macOS = m-processors
# only" rule), so this template has no on_intel block under on_macos.
# dodot has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts. Add both back when those features land.

class Dodot < Formula
  desc "A dotfiles manager that uses symlinks for live editing"
  homepage "https://github.com/arthur-debert/dodot"
  version "1.0.0-rc.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/dodot/releases/download/v1.0.0-rc.4/dodot-aarch64-apple-darwin.tar.gz"
      sha256 "4fdfae52bbbe91b2a4d8f37bfebc9ce5d2e8e146a660cf64362d3b0de8051536"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/dodot/releases/download/v1.0.0-rc.4/dodot-x86_64-linux-gnu.tar.gz"
      sha256 "9688d8ac85cd81c621bffad07c3585c913b52186159de38f20bf57c629ba4426"
    end
    on_arm do
      url "https://github.com/arthur-debert/dodot/releases/download/v1.0.0-rc.4/dodot-aarch64-linux-gnu.tar.gz"
      sha256 "ed2b1a8c9188fd1161ae87799a0ba346a621a14164beb017203f31b22be0bc24"
    end
  end

  def install
    # Homebrew cd's into the single top-level directory when the tarball
    # has one. dodot's tarballs are flat (binary at the archive root), so
    # the File.exist? branch normally hits; the Dir glob fallback covers
    # any future packaging change without breaking installs.
    executable = if File.exist?("dodot")
      "dodot"
    else
      Dir["*/dodot"].find { |path| File.file?(path) }
    end
    raise "Could not find dodot in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dodot --version")
  end
end
