# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotcat < Formula
  desc "A CLI utility for reading values from structured data files."
  homepage "https://github.com/arthur-debert/dotcat"
  version "0.9.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.5/dotcat_0.9.5_darwin_amd64.tar.gz"
      sha256 "8ab07c41b29e26fce659c25c04b18f9ae0a1b26e1634b7c1006afd9a3a255319"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.5/dotcat_0.9.5_darwin_arm64.tar.gz"
      sha256 "fba7e9edd2e643a641fd3ea136d4e818af1a0af3bd193f99a8d48528eaee82e2"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.5/dotcat_0.9.5_linux_amd64.tar.gz"
      sha256 "5f459354bc2b98db9742883f0461c6509349f93c32798d17ec8a136607bd81f6"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.5/dotcat_0.9.5_linux_arm64.tar.gz"
      sha256 "90a7c4dc16abbdde9c090f73da08b17ccc29bbe5b064921fb09bb8b17a081501"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  test do
    system "#{bin}/dotcat --version"
  end
end
