# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotcat < Formula
  desc "A CLI utility for reading values from structured data files."
  homepage "https://github.com/arthur-debert/dotcat"
  version "0.9.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.7/dotcat_0.9.7_darwin_amd64.tar.gz"
      sha256 "8f276cf19981a0b52f2dcfda2337ec36be64ea82c29dd6a279b5cee4570b044c"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.7/dotcat_0.9.7_darwin_arm64.tar.gz"
      sha256 "c9b1d53968acac1f2f0dbca0e9eb65bcb8ad17563ab8845d90431cc0c967d193"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.7/dotcat_0.9.7_linux_amd64.tar.gz"
      sha256 "d9a55907bd828745260462df3f358246009f02607f17ac414b899405d8697ad1"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.7/dotcat_0.9.7_linux_arm64.tar.gz"
      sha256 "672ad3b45c7f30abc28b6fcf3521918b4e3cdd7502b7d4408573417b45c2d565"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  test do
    system "#{bin}/dotcat --version"
  end
end
