# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotcat < Formula
  desc "A CLI utility for reading values from structured data files."
  homepage "https://github.com/arthur-debert/dotcat"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.4/dotcat_0.9.4_darwin_amd64.tar.gz"
      sha256 "1c51e73f06a03587879258fd60adb57b423e9a4d4a58ec90d77b3c8fe5aa6c04"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.4/dotcat_0.9.4_darwin_arm64.tar.gz"
      sha256 "bc712fbe8c88ff82456dc4cc5ba39d6ac89ae47ba68e15dbbe5f1ec41e26e853"

      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.4/dotcat_0.9.4_linux_amd64.tar.gz"
      sha256 "d0dc51c90128e5035ebed66f1c6b00b528c38d57657818f38da049f380faf318"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/dotcat/releases/download/v0.9.4/dotcat_0.9.4_linux_arm64.tar.gz"
      sha256 "c40990c869022a0af2ba6770882e0f266e3b805c7e55a887d88006c3030497f4"
      def install
        bin.install "dotcat"
        man1.install "man/man1/dotcat.1"
        bash_completion.install "completions/dotcat.bash" => "dotcat"
        zsh_completion.install "completions/_dotcat" => "_dotcat"
        fish_completion.install "completions/dotcat.fish"
      end
    end
  end

  test do
    system "#{bin}/dotcat --version"
  end
end
