# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# This formula installs `lexd`, the Lex CLI. The companion `lexd-lsp`
# language server ships separately as tarball-only artifacts on the
# GitHub Release for editor extensions to consume; it isn't installed
# via brew because end users don't invoke it directly.
#
# `lex-fmt/lex` ships macOS arm64 AND x86_64; linux x86_64 + aarch64
# (also musl + windows tarballs, but those aren't referenced from brew).

class Lexd < Formula
  desc "Command-line interface for the lex format"
  homepage "https://github.com/lex-fmt/lex"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0/lexd-aarch64-apple-darwin.tar.gz"
      sha256 "f05c1a5230da467419de94f86fec8c4cd64dbf8ccdb93dbb04b4add53befef5e"
    end
    on_intel do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0/lexd-x86_64-apple-darwin.tar.gz"
      sha256 "b94e82c152f74ca90b089bf50cbe95b83160eb6972ed1dcb816496271c7f7606"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0/lexd-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "70b0274d40f5655a639173fc03b75b1b9a77279e84a64f4373da3c34f8dd3898"
    end
    on_arm do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0/lexd-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b00143c9e1d552d4bef9bdf2e8216cc5c2c2304f91402a04baf604d531da35f8"
    end
  end

  def install
    # Existing lex-fmt/lex tarball layout: flat binary at root, named
    # `lexd` (matching the lexd-<target>.tar.gz pattern, where <target>
    # is encoded only in the filename, not the contents). File.exist?
    # handles that. The Dir glob fallback covers a future subdirectory
    # layout matching dodot/padz/burgertocow.
    executable = if File.exist?("lexd")
      "lexd"
    else
      Dir["*/lexd"].find { |path| File.file?(path) }
    end
    raise "Could not find lexd in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lexd --version")
  end
end
