# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# This formula installs `lexd`, the Lex CLI. The companion `lexd-lsp`
# language server ships separately as tarball-only artifacts on the
# GitHub Release for editor extensions to consume; it isn't installed
# via brew because end users don't invoke it directly.
#
# `lex-fmt/lex` ships macOS arm64 AND x86_64; linux x86_64 + aarch64
# (also musl + windows tarballs, but those aren't referenced from brew).

class Lexd < Formula
  desc "Command-line interface for the lex format"
  homepage "https://github.com/lex-fmt/lex"
  version "0.9.0-rc.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0-rc.2/lexd-aarch64-apple-darwin.tar.gz"
      sha256 "a170f4fccdea6c837fa653e793ebb6a5f8f8468d8c4192efad04b988b7810ede"
    end
    on_intel do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0-rc.2/lexd-x86_64-apple-darwin.tar.gz"
      sha256 "b598ae7a333700d541723953ba2f581fb25ad008d58fc8b699f7f4c1d092dfb4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0-rc.2/lexd-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c665cdcb00012685ea811cded2e31f258554f430a144691438d0281809143acb"
    end
    on_arm do
      url "https://github.com/lex-fmt/lex/releases/download/v0.9.0-rc.2/lexd-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "39e83ffa82ba02cdbba4f951730a613f119c7b8d2b2b8c7134281b27c800f06f"
    end
  end

  def install
    # Existing lex-fmt/lex tarball layout: flat binary at root, named
    # `lexd` (matching the lexd-<target>.tar.gz pattern, where <target>
    # is encoded only in the filename, not the contents). File.exist?
    # handles that. The Dir glob fallback covers a future subdirectory
    # layout matching dodot/padz/burgertocow.
    executable = if File.exist?("lexd")
      "lexd"
    else
      Dir["*/lexd"].find { |path| File.file?(path) }
    end
    raise "Could not find lexd in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lexd --version")
  end
end
