# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanodoc < Formula
  desc "A minimalist document bundler"
  homepage "https://github.com/arthur-debert/nanodoc"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.4.1/nanodoc_0.4.1_darwin_amd64.tar.gz"
      sha256 "7be8626df3db4771e7c3645efd1abd8028a3056a5ecf746e4e7e5d58cbb68b7f"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.4.1/nanodoc_0.4.1_darwin_arm64.tar.gz"
      sha256 "46a67844f0aa35258f598ef5716dfe4b766518078371f77971b0b4d838fed349"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.4.1/nanodoc_0.4.1_linux_amd64.tar.gz"
      sha256 "c67e3abd21e51ebab997c2e8c8af500e669f5bc2656d90cca90c52d0e30fee33"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.4.1/nanodoc_0.4.1_linux_arm64.tar.gz"
      sha256 "0f098a9ee885ec516f4cee770b1fe788cb36f92bc1632470d32f4bf26932d66f"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/nanodoc --help"
  end
end
