# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanodoc < Formula
  desc "A minimalist document bundler"
  homepage "https://github.com/arthur-debert/nanodoc"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.3.1/nanodoc_0.3.1_darwin_amd64.tar.gz"
      sha256 "6a659062107f47da791bc4077fbca8fb6a657ff7cbd97c688f8d31a7b6c38163"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.3.1/nanodoc_0.3.1_darwin_arm64.tar.gz"
      sha256 "a9efc93894b3d938135590962980f1bb60a57f7d316b9f529a53f9ef5f16220f"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.3.1/nanodoc_0.3.1_linux_amd64.tar.gz"
      sha256 "048c2ac0de902d7aaefc38e3008e9bfd8bd50d20c8b30b5aa8b09040cc4c499b"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc/releases/download/v0.3.1/nanodoc_0.3.1_linux_arm64.tar.gz"
      sha256 "0dfc25e9ffcbe3997b7eb0ab4bb5cc6db3d3749354872d1b9bfb6bc31094e8ed"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/nanodoc --help"
  end
end
