# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanodoc < Formula
  desc "A minimalist document bundler"
  homepage "https://github.com/arthur-debert/nanodoc-go"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.6/nanodoc_0.0.6_darwin_amd64.tar.gz"
      sha256 "3b95d63cd61af43c293a481f5e35c2593828893612b8bd081f6ec96c6bb511ce"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.6/nanodoc_0.0.6_darwin_arm64.tar.gz"
      sha256 "4780901b0d829230466504626673e718e1220c89868b7a2e1cf966fbf01ef6b0"

      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.6/nanodoc_0.0.6_linux_amd64.tar.gz"
      sha256 "3d34cbc8c8e498fb5c4816f5a83191a8c18812a775e6f1f8fb82e407006da85b"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/nanodoc-go/releases/download/v0.0.6/nanodoc_0.0.6_linux_arm64.tar.gz"
      sha256 "e119ab450a91d2036f98ac80d5d7d92ad335cd3259b4b16627bd02f9c20b0986"
      def install
        bin.install "nanodoc"

        # Install shell completions
        bash_completion.install "completions/nanodoc.bash"
        zsh_completion.install "completions/nanodoc.zsh"
        fish_completion.install "completions/nanodoc.fish"

        # Install man page
        man1.install "man/man1/nanodoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/nanodoc --help"
  end
end
