# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Padz < Formula
  desc "A simple command-line note-taking tool"
  homepage "https://github.com/arthur-debert/padz"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/padz/releases/download/v1.2.0/padz-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "e34117fc6879fcac0435a1f636d3d82743039057ad99b5c586383835a0e43bc3"

      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/padz/releases/download/v1.2.0/padz-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "050706cea4892fdb435282707b119bc0f6d5d6f88fc775d208e8a345b349ca30"

      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/padz/releases/download/v1.2.0/padz-cli_1.2.0_linux_amd64.tar.gz"
      sha256 "a5ed7ea06afb3268de403e22035902a27146e77bb56959fc3f0a2e81e83f7ced"
      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/padz/releases/download/v1.2.0/padz-cli_1.2.0_linux_arm64.tar.gz"
      sha256 "71a39c9b19d5ec3c0077635e8e2ed256fc962ec2c62f787da480f5aadb93ff87"
      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
  end

  test do
    system "#{bin}/padz --help"
  end
end
