# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow using sed. The generated output is pushed to the tap repo
# (HOMEBREW_TAP in release.yml).

class Padz < Formula
  desc "An ergonomic, context-aware scratch pad for the terminal — a good Unix citizen"
  homepage "https://github.com/arthur-debert/padz"
  version "1.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-aarch64-apple-darwin.tar.gz"
      sha256 "80cda41210b22c225bd3ea745cd39aaa9e12ac95891575a447d3d2085dd0558a"
    end
    on_intel do
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-x86_64-apple-darwin.tar.gz"
      sha256 "f5ea2f8acda210b6efe69e8d209f0fc66766eed32aa5ad13bbec25a876f5ede0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-x86_64-linux-gnu.tar.gz"
      sha256 "f748267d23e3ac23cc2e4b0983111360151cf171d96b2279e7582782d145c16f"
    end
    on_arm do
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-aarch64-linux-gnu.tar.gz"
      sha256 "e93191c918b06cb3d191894ff4f553f675d0d808cd7d9377279003e1861ed0f1"
    end
  end

  def install
    # Homebrew cd's into the single top-level directory when the tarball
    # has one — which ours does (`padz-<target>/padz`).
    # The Dir glob fallback covers reuse with flat tarballs or any other
    # packaging layout.
    executable = if File.exist?("padz")
      "padz"
    else
      Dir["*/padz"].find { |path| File.file?(path) }
    end
    raise "Could not find padz in extracted archive" unless executable
    bin.install executable

    # Generate completion scripts from the binary itself so they always
    # match the clap_complete wire protocol the binary implements.
    # padz's completion CLI is `padz completion --shell X print`,
    # which doesn't match any of Homebrew's generate_completions_from_executable
    # presets, so invoke manually.
    [
      [bash_completion/"padz",       "bash"],
      [zsh_completion/"_padz",       "zsh"],
      [fish_completion/"padz.fish",  "fish"],
    ].each do |path, shell|
      path.write Utils.safe_popen_read(bin/"padz", "completion", "--shell", shell, "print")
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/padz --version")
  end
end
