# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Padz < Formula
  desc "A simple command-line note-taking tool"
  homepage "https://github.com/arthur-debert/padz"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-cli_1.8.0_darwin_amd64.tar.gz"
      sha256 "87b47e705866332cca9cd95ef45ae84377a66a134792ac741083395b502a9d1e"

      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-cli_1.8.0_darwin_arm64.tar.gz"
      sha256 "a359836241833dc2b932cd1d01e3cb5cb07a71d487fa493f29aa68421de939e3"

      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-cli_1.8.0_linux_amd64.tar.gz"
      sha256 "79c95f5a5cd218dd5413132153bc5431e57a741c65cee691ffa244d5e18ac6ae"
      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/padz/releases/download/v1.8.0/padz-cli_1.8.0_linux_arm64.tar.gz"
      sha256 "2319c1b175288ff25d3ad1222251b664430e68fab9fc3aa29360ed0deadf473a"
      def install
        bin.install "padz"

        # Install shell completions
        bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
        zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
        fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")

        # Install man page
        man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")
      end
    end
  end

  test do
    system "#{bin}/padz --help"
  end
end
