# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow via .github/render-homebrew-formula.py. The generated output
# is pushed to the tap repo (HOMEBREW_TAP in release.yml).
#
# rustloc ships macOS arm64 AND x86_64 (intel + apple silicon) since the
# project's matrix already builds both. Linux ships x86_64 + aarch64.
# rustloc has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts.

class Rustloc < Formula
  desc "Rust-aware LOC counter that separates production code from tests — even in the same file"
  homepage "https://github.com/arthur-debert/rustloc"
  version "0.14.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.1/rustloc-aarch64-apple-darwin.tar.gz"
      sha256 "2e84a555bb2296669cdbcf3e9790f6717ae3569d489d23145c4d63a6e0fccd89"
    end
    on_intel do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.1/rustloc-x86_64-apple-darwin.tar.gz"
      sha256 "109b89ff59f304f7d8dfbb1497cd22a504b2ef970ad777d94c3c982900f39863"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.1/rustloc-x86_64-linux-gnu.tar.gz"
      sha256 "ccd46407d2d20d3d23a52e63872a0fd034a456fee4d40bc78462fb7cfd0cb0c4"
    end
    on_arm do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.1/rustloc-aarch64-linux-gnu.tar.gz"
      sha256 "e6ab095eb584e4781f6af7eea437b251a73de2af5dbfe86426d4448caf91bf40"
    end
  end

  def install
    # rustloc tarballs use the canonical subdirectory layout:
    # `rustloc-<target>/rustloc`. The Dir glob covers that;
    # File.exist? handles a future flat-root layout for portability.
    executable = if File.exist?("rustloc")
      "rustloc"
    else
      Dir["*/rustloc"].find { |path| File.file?(path) }
    end
    raise "Could not find rustloc in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustloc --version")
  end
end
