# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow via .github/render-homebrew-formula.py. The generated output
# is pushed to the tap repo (HOMEBREW_TAP in release.yml).
#
# rustloc ships macOS arm64 AND x86_64 (intel + apple silicon) since the
# project's matrix already builds both. Linux ships x86_64 + aarch64.
# rustloc has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts.

class Rustloc < Formula
  desc "Rust-aware LOC counter that separates production code from tests — even in the same file"
  homepage "https://github.com/arthur-debert/rustloc"
  version "0.14.0-rc.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.0-rc.1/rustloc-aarch64-apple-darwin.tar.gz"
      sha256 "4b4ce2b21223ddb5d713ea8d91d319ced3257cd93e1c40d2662b84f3af3e4c92"
    end
    on_intel do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.0-rc.1/rustloc-x86_64-apple-darwin.tar.gz"
      sha256 "737126389efbefa2e40dd53fcee3c2a38db6e6feca33d93fd6028602c2ea00bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.0-rc.1/rustloc-x86_64-linux-gnu.tar.gz"
      sha256 "96ffe73a19edbcbac5cd6c7b8e4fa3eb1e74e5bf97e70277feab282cb2efbebc"
    end
    on_arm do
      url "https://github.com/arthur-debert/rustloc/releases/download/v0.14.0-rc.1/rustloc-aarch64-linux-gnu.tar.gz"
      sha256 "92122937375d04b6c47d7bc2d832849d3f42afe3310f70dbb015d2b15aba419b"
    end
  end

  def install
    # rustloc tarballs use the canonical subdirectory layout:
    # `rustloc-<target>/rustloc`. The Dir glob covers that;
    # File.exist? handles a future flat-root layout for portability.
    executable = if File.exist?("rustloc")
      "rustloc"
    else
      Dir["*/rustloc"].find { |path| File.file?(path) }
    end
    raise "Could not find rustloc in extracted archive" unless executable
    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustloc --version")
  end
end
