# This file is generated by .github/workflows/release.yml on every release.
# DO NOT EDIT by hand — your changes will be overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow via .github/render-homebrew-formula.py. The generated output
# is pushed to the tap repo (HOMEBREW_TAP in release.yml).
#
# simple-gal ships macOS arm64 only (matches the project's "macOS = m-processors
# only" rule), so this template has no on_intel block under on_macos.
# simple-gal has no `completion --shell` CLI yet, so this template doesn't
# generate shell completion scripts. Add both back when those features land.

class SimpleGal < Formula
  desc "A minimal static site generator for fine art photography portfolios"
  homepage "https://github.com/arthur-debert/simple-gal"
  version "0.20.1-rc.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/simple-gal/releases/download/v0.20.1-rc.1/simple-gal-aarch64-apple-darwin.tar.gz"
      sha256 "47a75de9def9788a605f2642f4cd2b2619b693ce0524ada0a2e644d6141db9eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/simple-gal/releases/download/v0.20.1-rc.1/simple-gal-x86_64-linux-gnu.tar.gz"
      sha256 "941309e78c3e9d7135a27854b6c66af7ac49c97c7ceaca1bd7d918baa1290597"
    end
    on_arm do
      url "https://github.com/arthur-debert/simple-gal/releases/download/v0.20.1-rc.1/simple-gal-aarch64-linux-gnu.tar.gz"
      sha256 "5567f09106efe9abc7840287426637a15c3ad55c3c105ebf22609eabd651e8e8"
    end
  end

  def install
    bin_name = "simple-gal"
    # Three layouts handled in priority order:
    #   1. Canonical: binary at root with the package name (e.g. `simple-gal`).
    #      Used by future packaging.
    #   2. Renamed-flat: binary at root renamed to `<bin_name>-<target>`
    #      (e.g. `simple-gal-x86_64-linux-gnu`). Current simple-gal packaging,
    #      preserved for backwards-compat with `simple-gal-action`.
    #   3. Subdirectory: binary inside a per-target dir (`<target>/<bin_name>`).
    #      Used by dodot/padz; covered for portability.
    if File.exist?(bin_name)
      bin.install bin_name
    elsif (flat = Dir.children(".").find { |p| File.file?(p) && p.start_with?("#{bin_name}-") })
      # bin.install src => dst renames as it copies, so the user gets
      # `simple-gal` on PATH regardless of which target tarball was downloaded.
      bin.install flat => bin_name
    elsif (nested = Dir["*/#{bin_name}"].find { |p| File.file?(p) })
      bin.install nested
    else
      raise "Could not find #{bin_name} in extracted archive (checked root, root/#{bin_name}-*, */#{bin_name})"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/simple-gal --version")
  end
end
