# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdh < Formula
  desc "A simple command-line todo list manager"
  homepage "https://github.com/arthur-debert/tdh"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.1.3/tdh_0.1.3_darwin_amd64.tar.gz"
      sha256 "822517da0138e5593806ebd1c515beee594d6b2f90a80de7914d4f7d22d2fed4"

      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.1.3/tdh_0.1.3_darwin_arm64.tar.gz"
      sha256 "cd24089f6c2f5eb72b8f15e5bd66ea3e63762130772690392ad35b3a9de2c936"

      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.1.3/tdh_0.1.3_linux_amd64.tar.gz"
      sha256 "dd92dfb6b199d834ee7da5bcf2d9dc70cb2e57f116070c50ee04dcdd7e0940ef"
      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.1.3/tdh_0.1.3_linux_arm64.tar.gz"
      sha256 "97b1c9296b4601df2516af1059939b2d2ed37030c5d016beed2131476564fb62"
      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
  end

  test do
    system "#{bin}/tdh --help"
  end
end
