# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdh < Formula
  desc "A simple command-line todo list manager"
  homepage "https://github.com/arthur-debert/tdh"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.2.0/tdh_0.2.0_darwin_amd64.tar.gz"
      sha256 "dfbe501df0b7d62128459d88d92aec68d17c57914433b206de88a6e9a93f3768"

      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.2.0/tdh_0.2.0_darwin_arm64.tar.gz"
      sha256 "8393fa210063f74bbd16a14b9a88b299273a3214eaaf7fa8c4001b8307eb78a2"

      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.2.0/tdh_0.2.0_linux_amd64.tar.gz"
      sha256 "58b91c910550b20642b6347c05ed4c2e1c449de1d403629e5ea2d8f46cb50d4a"
      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/tdh/releases/download/v0.2.0/tdh_0.2.0_linux_arm64.tar.gz"
      sha256 "a329af5621c8888562c7b54d27b6f9d88a810bc063b0baab89cdd92243d0be06"
      def install
        bin.install "tdh"

        # Install shell completions
        bash_completion.install "completions/tdh.bash" if File.exist?("completions/tdh.bash")
        zsh_completion.install "completions/_tdh" if File.exist?("completions/_tdh")
        fish_completion.install "completions/tdh.fish" if File.exist?("completions/tdh.fish")

        # Install man page
        man1.install "man/man1/tdh.1.gz" if File.exist?("man/man1/tdh.1.gz")
      end
    end
  end

  test do
    system "#{bin}/tdh --help"
  end
end
