# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Too < Formula
  desc "A simple command-line todo list manager"
  homepage "https://github.com/arthur-debert/too"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/too/releases/download/v0.7.3/too_0.7.3_darwin_amd64.tar.gz"
      sha256 "10f14d3122981b66dfc7f7f7e7b51fca087380bce4156289081ee80d0371ff49"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/too/releases/download/v0.7.3/too_0.7.3_darwin_arm64.tar.gz"
      sha256 "6b5a637409cfd304531edd0c450334da72a21a8d9da26b4db3745fe0bc469097"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.7.3/too_0.7.3_linux_amd64.tar.gz"
      sha256 "eb8673506a59273aa3df169c9e0c0a6603ef3374c8c9c45c7119855324e00c5f"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.7.3/too_0.7.3_linux_arm64.tar.gz"
      sha256 "45bf50610d3ce768c942029ecb0a52ccae0b7be46e8025f01ccef09c3ddfb2fb"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  test do
    system "#{bin}/too --help"
  end
end
