# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Too < Formula
  desc "A simple command-line todo list manager"
  homepage "https://github.com/arthur-debert/too"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/too/releases/download/v0.5.0/too_0.5.0_darwin_amd64.tar.gz"
      sha256 "6cb2496ee40a11d426178776bdf4b839119dc842a6271ee263007ea97e23fd5f"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/too/releases/download/v0.5.0/too_0.5.0_darwin_arm64.tar.gz"
      sha256 "4c95d9773b1d17b85082b6da61bb6b4b825d361432afd1233d1cb6c1449bdfe6"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.5.0/too_0.5.0_linux_amd64.tar.gz"
      sha256 "cfb7bc591ace03b0459850c34f7542879d882e5e27fbdc6432434349ac0ef72d"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.5.0/too_0.5.0_linux_arm64.tar.gz"
      sha256 "7a4374e5850ff8cdaf29738762b0857efa51570f3e597ddc499eb5d9df0a937a"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  test do
    system "#{bin}/too --help"
  end
end
