# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Too < Formula
  desc "A simple command-line todo list manager"
  homepage "https://github.com/arthur-debert/too"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/too/releases/download/v0.3.0/too_0.3.0_darwin_amd64.tar.gz"
      sha256 "c796c77947f3e783506438a51a4a42c64d687fc49b51dd482233b95441aec9d7"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/too/releases/download/v0.3.0/too_0.3.0_darwin_arm64.tar.gz"
      sha256 "aaa4ce98978c13ae272a4b17ac4a9406756acea787ffb98f30f7a5f1ae4f1e66"

      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.3.0/too_0.3.0_linux_amd64.tar.gz"
      sha256 "9733dff5a0cf2d9fa6d3db7bd9f38c0f0e5be058ff58091c2612a70adf4f2bf1"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/too/releases/download/v0.3.0/too_0.3.0_linux_arm64.tar.gz"
      sha256 "eda78d1d1cbe5cba8135fe2446334b7f85b07187418f911be07e403e6c636779"
      def install
        bin.install "too"

        # Install shell completions
        bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
        zsh_completion.install "completions/_too" if File.exist?("completions/_too")
        fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")

        # Install man page
        man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")
      end
    end
  end

  test do
    system "#{bin}/too --help"
  end
end
