# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.12.3/treex_0.12.3_darwin_amd64.tar.gz"
      sha256 "f2ae5f4fcc45746268ce5ea8e5f99f8362d33966e7e914d7f988e9a7530a79d8"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.12.3/treex_0.12.3_darwin_arm64.tar.gz"
      sha256 "9de268129a9c7d6d6b5d49e8179dccb7a6f654732ebb5a802b4f59d73c48ef34"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.12.3/treex_0.12.3_linux_amd64.tar.gz"
      sha256 "02495382b46fb676f3fe118fac9155c93502e13e0d4060158c6774eb029b8c19"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.12.3/treex_0.12.3_linux_arm64.tar.gz"
      sha256 "942eaf187f0fdb4ef8f00039ee30236e72c8c42a625ba5063dc902188e6aaf6c"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    system "#{bin}/treex --version"
  end
end
