# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.7.1/treex_0.7.1_darwin_amd64.tar.gz"
      sha256 "8febd58b3f9a210f10559e91fcd701dea7daef78238e2cc0cab06cbb4ba1c9f7"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.7.1/treex_0.7.1_darwin_arm64.tar.gz"
      sha256 "050feb6da7aba93c565a780040a11eb3c348c32e08b5d548bc4cb2136facccb1"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.7.1/treex_0.7.1_linux_amd64.tar.gz"
      sha256 "4ad42647fb66bffc9240712432cb4b35f3a7bf638bb02aa225c4baa4fa98009d"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.7.1/treex_0.7.1_linux_arm64.tar.gz"
      sha256 "9bf1cafd97cedc1fd09d46c3ac66972dff02fd93974f682fa697a1e68ec21bf2"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    system "#{bin}/treex --version"
  end
end
