# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treex < Formula
  desc "A CLI file viewer for annotated file trees"
  homepage "https://github.com/arthur-debert/treex"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/treex/releases/download/v0.9.0/treex_0.9.0_darwin_amd64.tar.gz"
      sha256 "ceb9e91c58d0ebf3338daa436b28df37604f39b3c3cf6c096f0f3b798ed80ef0"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/treex/releases/download/v0.9.0/treex_0.9.0_darwin_arm64.tar.gz"
      sha256 "499500040324d5d761a7999c2a3448abbba0a7dacde86cacf480d7a362c230c0"

      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.9.0/treex_0.9.0_linux_amd64.tar.gz"
      sha256 "f21422ac92a7fc5af6c1791657ccd5b625584d31cec2bb1fc2a5f263e24316c2"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/treex/releases/download/v0.9.0/treex_0.9.0_linux_arm64.tar.gz"
      sha256 "2dd57559124fe42b483b8c524b64df1bbbbb382bc242868ac353d17fa93a9d5e"
      def install
        bin.install "treex"
        man1.install "man/man1/treex.1"
        bash_completion.install "completions/treex.bash" => "treex"
        zsh_completion.install "completions/_treex" => "_treex"
        fish_completion.install "completions/treex.fish"
      end
    end
  end

  test do
    system "#{bin}/treex --version"
  end
end
