# This file is generated on every release by the arthur-debert/release
# rust-cli.yml workflow. DO NOT EDIT by hand — your changes will be
# overwritten on the next tag.
#
# Placeholders are of the form {{NAME}} and substituted by the release
# workflow via scripts/render-brew-formula.py. The generated output is
# pushed to the tap repo (HOMEBREW_TAP).
#
# Canonical layout: macOS arm64 only (no on_intel under on_macos),
# Linux x86_64 + aarch64. Add an on_intel block under on_macos and an
# extra URL/SHA pair if a project needs Intel-mac.
# Add `on_arm` under on_linux for aarch64-musl, etc.

require "download_strategy"

# Inlined private-release downloader. Reads HOMEBREW_GITHUB_API_TOKEN
# and translates the public release URL into the authenticated assets
# API endpoint. Without this, brew install 404s on private-repo
# releases. Generated by arthur-debert/release; do not edit by hand.
class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  require "utils/github"

  def initialize(url, name, version, **meta)
    super
    parse_url_pattern
    set_github_token
  end

  def parse_url_pattern
    url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
    raise CurlDownloadStrategyError, "Invalid url pattern for GitHub Release." unless @url =~ url_pattern
    _, @owner, @repo, @tag, @filename = *@url.match(url_pattern).to_a
  end

  def set_github_token
    @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
    raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required for private-repo brew installs." unless @github_token
  end

  def asset_id
    @asset_id ||= begin
      release_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"
      release = GitHub.open_api(release_url)
      asset = release["assets"]&.find { |a| a["name"] == @filename }
      raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}." unless asset
      asset["id"]
    end
  end

  def _fetch(url:, resolved_url:, timeout:)
    api_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    curl_download api_url,
                  "--header", "Accept: application/octet-stream",
                  "--header", "Authorization: Bearer #{@github_token}",
                  to: temporary_path, timeout: timeout
  end
end
class Waveterm < Formula
  desc "WaveTerm: semi-grid rendering platform for modern terminals"
  homepage "https://github.com/arthur-debert/wave-term"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthur-debert/wave-term/releases/download/v0.0.1/waveterm-aarch64-apple-darwin.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fa2c2984a714931c51e41b155a4719909fc45ac9b58137f88469b7d6b23eaf02"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthur-debert/wave-term/releases/download/v0.0.1/waveterm-x86_64-unknown-linux-gnu.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8b3b432a22a3a134d05400add7aea36f9581444f77312547d4a4a6e80918fdc5"
    end
    on_arm do
      url "https://github.com/arthur-debert/wave-term/releases/download/v0.0.1/waveterm-aarch64-unknown-linux-gnu.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "61d59e608f33ba2af8f4614615e3eeb9473b6434b972a182a267859e2cdbbd6f"
    end
  end

  def install
    # Canonical tarball layout is <bin_name>/<bin_name> (subdir). Older
    # tarballs may be flat-at-root; the Dir glob covers both shapes so
    # consumers can migrate without breaking installs in flight.
    executable = Dir["*/waveterm"].find { |path| File.file?(path) } ||
                 (File.exist?("waveterm") ? "waveterm" : nil)
    raise "Could not find waveterm in extracted archive" unless executable

    bin.install executable
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/waveterm --version")
  end
end
