# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TxxtLsp < Formula
  desc "Language Server Protocol server for the txxt markup language."
  homepage "https://github.com/arthur-debert/txxt"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-lsp_0.0.12_darwin_amd64.tar.gz"
      sha256 "e9d9ad924185d4c3cd7f2203424658d2b08072ed1854354640f45ad34dd7cc61"

      def install
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-lsp_0.0.12_darwin_arm64.tar.gz"
      sha256 "7f9d29bf00e3fc7f540b364ef749154677396efa16a5e1ce2f104e2c5eada4d7"

      def install
        bin.install "txxt-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-lsp_0.0.12_linux_amd64.tar.gz"
      sha256 "b8c020f9d7c8ed95a394bdbed13c542b841258e045f062486458d8178875542f"
      def install
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-lsp_0.0.12_linux_arm64.tar.gz"
      sha256 "ac0f79bd3ea8bbc5e9ebcafbc662fd004bafd1d13dae88c03fcea58129d389a1"
      def install
        bin.install "txxt-lsp"
      end
    end
  end

  test do
    system "#{bin}/txxt-lsp --help"
  end
end
