# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txxt < Formula
  desc "A parser for the txxt markup language with multiple output formats."
  homepage "https://github.com/arthur-debert/txxt"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-cli_0.0.12_darwin_amd64.tar.gz"
      sha256 "c97c30cfea92ead82c4d9e34a7b4910e66f1829e9176102da9fc94f3a5f262f7"

      def install
        bin.install "txxt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-cli_0.0.12_darwin_arm64.tar.gz"
      sha256 "e3b35b32f10b147b8c0631d5fb1dc78d5ff34ec6e22ebee8fc57c07eb0f00751"

      def install
        bin.install "txxt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-cli_0.0.12_linux_amd64.tar.gz"
      sha256 "29e63ca6557d689c374a8b3afbb12cc9fde01e6536f7a3f9490335408dd34d09"
      def install
        bin.install "txxt"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.12/txxt-cli_0.0.12_linux_arm64.tar.gz"
      sha256 "964add08f431c23e3b04b7a8002025f9e99112220d1c3fcc327db9674486f138"
      def install
        bin.install "txxt"
      end
    end
  end

  test do
    system "#{bin}/txxt --help"
  end
end
