# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TxxtLsp < Formula
  desc "Language Server Protocol server for the txxt markup language."
  homepage "https://github.com/arthur-debert/txxt"
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.16/txxt-lsp_0.0.16_darwin_amd64.tar.gz"
      sha256 "25e76c8df1253647774529fefcc80a19bc926ba1a8094f1cf005fb71a530a8d9"

      def install
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.16/txxt-lsp_0.0.16_darwin_arm64.tar.gz"
      sha256 "984c6d9878ef7ca77722cac0312c2df079311a0cc37fa21b8f2a3a6e7f974d83"

      def install
        bin.install "txxt-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.16/txxt-lsp_0.0.16_linux_amd64.tar.gz"
      sha256 "d5c30611623b14c12550b3c26110afb870ab6aaaeabaf2a775cd8a6be0fdaca6"
      def install
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.16/txxt-lsp_0.0.16_linux_arm64.tar.gz"
      sha256 "7153d74549df11452627e729b0f835db34d525459a097edf0baf7eb397db1005"
      def install
        bin.install "txxt-lsp"
      end
    end
  end

  test do
    system "#{bin}/txxt-lsp --help"
  end
end
