# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txxt < Formula
  desc "A parser for the txxt markup language with multiple output formats."
  homepage "https://github.com/arthur-debert/txxt"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.4/txxt_0.0.4_darwin_amd64.tar.gz"
      sha256 "79f004be9c8afa3cfda9e3b667059fdfc913f7dddd234ba2013082edd282fd84"

      def install
        bin.install "txxt-parser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.4/txxt_0.0.4_darwin_arm64.tar.gz"
      sha256 "596a27b6ebc44679921a59ddb551bea4d1f9a5d70f3a13bc3c7e330d5b96da1d"

      def install
        bin.install "txxt-parser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.4/txxt_0.0.4_linux_amd64.tar.gz"
      sha256 "6186d03e64e17601f121d41b8d24d87f4bf5e4f2225f4cfad614deebac727114"
      def install
        bin.install "txxt-parser"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.4/txxt_0.0.4_linux_arm64.tar.gz"
      sha256 "6d58e2bb69ea18c13779639c10d7bac753278319d0917aa7565c47b012a24a81"
      def install
        bin.install "txxt-parser"
      end
    end
  end

  test do
    system "#{bin}/txxt-parser --help"
  end
end
