# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txxt < Formula
  desc "A parser for the txxt markup language with multiple output formats."
  homepage "https://github.com/arthur-debert/txxt"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.8/txxt_0.0.8_darwin_amd64.tar.gz"
      sha256 "308e046272e57c961d2936bb6226e9938b25bbe8502a87b1813a0bbd7d9d02df"

      def install
        bin.install "txxt"
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.8/txxt_0.0.8_darwin_arm64.tar.gz"
      sha256 "5977a0d54e40a7303e71c9aa2519c7fd15ab669bb8864a45e77d012b7599f3ce"

      def install
        bin.install "txxt"
        bin.install "txxt-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.8/txxt_0.0.8_linux_amd64.tar.gz"
      sha256 "d905804d81c9a31b23f642b97b18afae50cab8baf90d38a89755c760dd0f9a42"
      def install
        bin.install "txxt"
        bin.install "txxt-lsp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/arthur-debert/txxt/releases/download/v0.0.8/txxt_0.0.8_linux_arm64.tar.gz"
      sha256 "b50c2eb6ed2a50f13ced4d8163ffee6939c5a5eb9da79b2d3f3de307bbb5ac33"
      def install
        bin.install "txxt"
        bin.install "txxt-lsp"
      end
    end
  end

  test do
    system "#{bin}/txxt --help"
  end
end
